version: "3.3"

services: 
  db:
    image: mongo:latest
    container_name: mongo_compose
    ports:
      - "27017:27017"
    networks: 
      - "custom"
    environment: 
      # MONGO_INITDB_ROOT_USERNAME: "root"
      # MONGO_INITDB_ROOT_PASSWORD: "password"
      MONGO_INITDB_DATABASE: "database_for_persons"
    # volumes:
    #   - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  mongo-express:
    image: mongo-express
    container_name: mexpress_compose
    restart: always
    ports:
      - "8081:8081"
    networks: 
      - "custom"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: DASistemas
      ME_CONFIG_BASICAUTH_PASSWORD: ex-especial567
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_SERVER: db
    depends_on: 
      - "db"

  golang-data:
    build: 
      context: ./Contenedor C/
    container_name: golang_getter
    networks: 
      - "custom"
    depends_on: 
      - "db"
    command: go run scraper.go

  golang-api:
    build: 
      context: ./Contenedor D/
    container_name: golang_server
    ports:
      - "7777:7777"
    networks: 
      - "custom"
    depends_on: 
      - "db"
    command: go run my_api.go



networks:
  custom:
    driver: bridge